/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSection: typeof import('./components/partials/about/AboutSection.vue')['default']
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    BackgroundText: typeof import('./components/partials/about/BackgroundText.vue')['default']
    DefaultCard: typeof import('./components/partials/about/DefaultCard.vue')['default']
    FooterBackground: typeof import('./components/partials/FooterBackground.vue')['default']
    FooterOverlay: typeof import('./components/FooterOverlay.vue')['default']
    HeaderOverlay: typeof import('./components/HeaderOverlay.vue')['default']
    HeroBackgroundTag: typeof import('./components/partials/index/HeroBackgroundTag.vue')['default']
    HeroButtonIndicator: typeof import('./components/partials/index/HeroButtonIndicator.vue')['default']
    HeroContent: typeof import('./components/partials/index/HeroContent.vue')['default']
    HeroCTA: typeof import('./components/partials/index/HeroCTA.vue')['default']
    HeroHeading: typeof import('./components/partials/index/HeroHeading.vue')['default']
    IndexFirstSection: typeof import('./components/partials/index/IndexFirstSection.vue')['default']
    IndexSecondSection: typeof import('./components/partials/index/IndexSecondSection.vue')['default']
    IndexThirdSection: typeof import('./components/partials/index/IndexThirdSection.vue')['default']
    LayoutDivider: typeof import('./components/partials/LayoutDivider.vue')['default']
    LinkCTA: typeof import('./components/LinkCTA.vue')['default']
    NavOverlay: typeof import('./components/NavOverlay.vue')['default']
    PreviousButton: typeof import('./components/partials/PreviousButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollIndicator: typeof import('./components/partials/ScrollIndicator.vue')['default']
    SidebarOverlay: typeof import('./components/SidebarOverlay.vue')['default']
    SocialCard: typeof import('./components/partials/about/SocialCard.vue')['default']
    SocialLink: typeof import('./components/partials/about/SocialLink.vue')['default']
    ToggleButton: typeof import('./components/partials/ToggleButton.vue')['default']
  }
}
